on: [push]

jobs:
  docker_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: getting docker build
        uses: docker/setup-buildx-action@v2
      # Use the output from the `hello` step
      - name: logging in to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ewing-ceg3120/angular-site:latest
